-- MEDIA JAKTIM DATABASE SETUP
create table if not exists articles (
 id bigint generated by default as identity primary key,
 title text not null,
 slug text unique,
 category text,
 excerpt text,
 content text,
 image text,
 status text default 'published',
 author text default 'Admin',
 created_at timestamp with time zone default now()
);

alter table articles enable row level security;

create policy "public read articles"
on articles
for select
using (true);

create policy "public insert articles"
on articles
for insert
with check (true);

create policy "public update articles"
on articles
for update
using (true);
